# Docker
# Yulian Kisil id:128371

version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    ports:
      - "8080:8080"
      - "8082:8082"
    command: ["npm", "start"]
#    volumes:
#      - .:/app
